
services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nanimiru_db
      MARIADB_USER: nanimiru_db_user
      MARIADB_PASSWORD: nanimiru_db_pwd
    volumes:
      - database_nanimiru:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_nanimiru: